### PR TITLE
add jxl_tool to comparison viewer

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Comment by mo271** [comment]
without it I get

```
FAILED: tools/comparison_viewer/compare_images 
: && /usr/bin/clang++ -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR -fno-rtti -O2 -g -DNDEBUG -fPIE -pie tools/comparison_viewer/CMakeFiles/compare_images.dir/compare_images_autogen/mocs_compilation.cpp.o tools/comparison_viewer/CMakeFiles/compare_images.dir/compare_images.cc.o tools/comparison_viewer/CMakeFiles/compare_images.dir/settings.cc.o tools/comparison_viewer/CMakeFiles/compare_images.dir/split_image_renderer.cc.o tools/comparison_viewer/CMakeFiles/compare_images.dir/split_image_view.cc.o -o tools/comparison_viewer/compare_images  -Wl,-rpath,/home/firsching/libjxl/build/lib:/home/firsching/libjxl/build/third_party/brotli  tools/comparison_viewer/libimage_loading.a  tools/libicc_detect.a  lib/libjxl_extras-internal.a  lib/libjxl_threads.so.0.10.2  /usr/lib/x86_64-linux-gnu/libgif.so  /usr/lib/x86_64-linux-gnu/libjpeg.so  third_party/sjpeg/libsjpeg.a  /usr/lib/x86_64-linux-gnu/libpng.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libOpenEXR-3_1.so  /usr/lib/x86_64-linux-gnu/libOpenEXRUtil-3_1.so  /usr/lib/x86_64-linux-gnu/libOpenEXRCore-3_1.so  /usr/lib/x86_64-linux-gnu/libIex-3_1.so  /usr/lib/x86_64-linux-gnu/libIlmThread-3_1.so  /usr/lib/x86_64-linux-gnu/libImath-3_1.so  lib/libjpegli-static.a  third_party/liblcms2.a  /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6.4.2  /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6.4.2  /usr/lib/x86_64-linux-gnu/libQt6Core.so.6.4.2  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so  lib/libjxl-internal.a  third_party/highway/libhwy.a  third_party/brotli/libbrotlidec.so.1.0.9  third_party/brotli/libbrotlienc.so.1.0.9  third_party/brotli/libbrotlicommon.so.1.0.9  -lm  lib/libjxl_cms.so.0.10.2  /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so  /usr/lib/x86_64-linux-gnu/libxcb.so && :
/usr/bin/ld: tools/comparison_viewer/libimage_loading.a(image_loading.cc.o): in function `jpegxl::tools::loadImage(QString const&, QByteArray const&, float, QString const&)':
/home/firsching/libjxl/tools/comparison_viewer/image_loading.cc:73:(.text+0x33f): undefined reference to `jpegxl::tools::NoMemoryManager()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[603/605] Building CXX object tools/comparison_viewer/CMakeFiles/compare_codecs.dir/codec_comparison_window.cc.o
ninja: build stopped: subcommand failed.

```

**Comment by mo271** [comment]
This was introduced by #3561. Not sure why none of our tests caught it!?

**Review by jonsneyers — APPROVED** [review]
