### ISSUE TITLE
Tests fail to build with LTO enabled

### ISSUE THREAD

**Issue by juw** [libjxl/libjxl#4152]
Dear maintainers,

in Debian it was tried to build version 0.11.1 while enabling LTO (see [1] for the full build log on i386 but on other architectures it faild with the same problem). When enabling LTO, there seems to be an undefined reference to `jxl::extras::PackedFrame::~PackedFrame()` for several tests, e.g.:
```
[334/418] : && /usr/bin/c++ -g -O2 -ffile-prefix-map=/build/reproducible-path/jpeg-xl-0.11.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fexcess-precision=fast -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR -Wdate-time -D_FORTIFY_SOURCE=2 -fno-rtti -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now      -fPIE -pie -Wl,--dependency-file=lib/CMakeFiles/color_description_test.dir/link.d lib/CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o -o lib/tests/color_description_test  -Wl,-rpath,/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib  lib/libjxl_testlib-internal.a  lib/libjxl_extras-internal.a  /usr/lib/i386-linux-gnu/libgtest_main.a  /usr/lib/i386-linux-gnu/libgtest.a  lib/libjxl-internal.a  /usr/lib/i386-linux-gnu/libhwy.so  /usr/lib/i386-linux-gnu/libbrotlidec.so  /usr/lib/i386-linux-gnu/libbrotlicommon.so  /usr/lib/i386-linux-gnu/libbrotlienc.so  lib/libjxl_cms.so.0.11.1  lib/libjxl_threads.so.0.11.1  /usr/lib/i386-linux-gnu/libgif.so  /usr/lib/i386-linux-gnu/libjpeg.so  /usr/lib/i386-linux-gnu/libpng.so  /usr/lib/i386-linux-gnu/libz.so  /usr/lib/i386-linux-gnu/libOpenEXR-3_1.so  /usr/lib/i386-linux-gnu/libOpenEXRUtil-3_1.so  /usr/lib/i386-linux-gnu/libOpenEXRCore-3_1.so  /usr/lib/i386-linux-gnu/libIex-3_1.so  /usr/lib/i386-linux-gnu/libIlmThread-3_1.so  /usr/lib/i386-linux-gnu/libImath-3_1.so && cd /build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib && /usr/bin/cmake -D TEST_TARGET=color_description_test -D TEST_EXECUTABLE=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib/tests/color_description_test -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=color_description_test_TESTS -D CTEST_FILE=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib/color_description_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=240 -D TEST_DISCOVERY_EXTRA_ARGS= -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake-3.31/Modules/GoogleTestAddTests.cmake
FAILED: lib/tests/color_description_test lib/color_description_test[1]_tests.cmake /build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib/color_description_test[1]_tests.cmake 
: && /usr/bin/c++ -g -O2 -ffile-prefix-map=/build/reproducible-path/jpeg-xl-0.11.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fexcess-precision=fast -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR -Wdate-time -D_FORTIFY_SOURCE=2 -fno-rtti -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now      -fPIE -pie -Wl,--dependency-file=lib/CMakeFiles/color_description_test.dir/link.d lib/CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o -o lib/tests/color_description_test  -Wl,-rpath,/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib  lib/libjxl_testlib-internal.a  lib/libjxl_extras-internal.a  /usr/lib/i386-linux-gnu/libgtest_main.a  /usr/lib/i386-linux-gnu/libgtest.a  lib/libjxl-internal.a  /usr/lib/i386-linux-gnu/libhwy.so  /usr/lib/i386-linux-gnu/libbrotlidec.so  /usr/lib/i386-linux-gnu/libbrotlicommon.so  /usr/lib/i386-linux-gnu/libbrotlienc.so  lib/libjxl_cms.so.0.11.1  lib/libjxl_threads.so.0.11.1  /usr/lib/i386-linux-gnu/libgif.so  /usr/lib/i386-linux-gnu/libjpeg.so  /usr/lib/i386-linux-gnu/libpng.so  /usr/lib/i386-linux-gnu/libz.so  /usr/lib/i386-linux-gnu/libOpenEXR-3_1.so  /usr/lib/i386-linux-gnu/libOpenEXRUtil-3_1.so  /usr/lib/i386-linux-gnu/libOpenEXRCore-3_1.so  /usr/lib/i386-linux-gnu/libIex-3_1.so  /usr/lib/i386-linux-gnu/libIlmThread-3_1.so  /usr/lib/i386-linux-gnu/libImath-3_1.so && cd /build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib && /usr/bin/cmake -D TEST_TARGET=color_description_test -D TEST_EXECUTABLE=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib/tests/color_description_test -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=color_description_test_TESTS -D CTEST_FILE=/build/reproducible-path/jpeg-xl-0.11.1/obj-i686-linux-gnu/lib/color_description_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=240 -D TEST_DISCOVERY_EXTRA_ARGS= -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake-3.31/Modules/GoogleTestAddTests.cmake
/usr/bin/ld: lib/libjxl_extras-internal.a(exr.cc.o): in function `jxl::extras::PackedImage::BitsPerChannel(JxlDataType)':
./obj-i686-linux-gnu/./lib/extras/packed_image.h:100:(.text+0x1b3): undefined reference to `jxl::Debug(char const*, ...)'
/usr/bin/ld: lib/libjxl_extras-internal.a(exr.cc.o): in function `jxl::extras::DecodeImageEXR(jxl::Span<unsigned char const>, jxl::extras::ColorHints const&, jxl::extras::PackedPixelFile*, jxl::SizeConstraints const*)':
./obj-i686-linux-gnu/./lib/extras/dec/exr.cc:124:(.text+0x2b9): undefined reference to `jxl::StatusMessage(jxl::Status, char const*, ...)'
/usr/bin/ld: ./obj-i686-linux-gnu/./lib/extras/dec/exr.cc:153:(.text+0x4db): undefined reference to `jxl::extras::PackedFrame::Create(unsigned int, unsigned int, JxlPixelFormat const&)'
/usr/bin/ld: ./obj-i686-linux-gnu/./lib/extras/dec/exr.cc:153:(.text+0x514): undefined reference to `jxl::StatusMessage(jxl::Status, char const*, ...)'
/usr/bin/ld: lib/libjxl_extras-internal.a(exr.cc.o): in function `jxl::extras::PackedFrame& std::vector<jxl::extras::PackedFrame, std::allocator<jxl::extras::PackedFrame> >::emplace_back<jxl::extras::PackedFrame>(jxl::extras::PackedFrame&&)':
/usr/include/c++/14/bits/vector.tcc:123:(.text+0xdad): undefined reference to `void std::vector<jxl::extras::PackedFrame, std::allocator<jxl::extras::PackedFrame> >::_M_realloc_append<jxl::extras::PackedFrame>(jxl::extras::PackedFrame&&)'
/usr/bin/ld: lib/libjxl_extras-internal.a(exr.cc.o): in function `jxl::extras::DecodeImageEXR(jxl::Span<unsigned char const>, jxl::extras::ColorHints const&, jxl::extras::PackedPixelFile*, jxl::SizeConstraints const*)':
./obj-i686-linux-gnu/./lib/extras/dec/exr.cc:157:(.text.unlikely+0x138): undefined reference to `jxl::extras::PackedFrame::~PackedFrame()'
/usr/bin/ld: lib/libjxl_extras-internal.a(exr.cc.o): in function `jxl::StatusOr<jxl::extras::PackedFrame>::~StatusOr()':
./obj-i686-linux-gnu/./lib/jxl/base/status.h:337:(.text.unlikely+0x150): undefined reference to `jxl::extras::PackedFrame::~PackedFrame()'
```
Building without LTO works just fine (see [2] for the full build log for comparison), so for now LTO is disabled in the debian builds (it used to work though for version 0.10.2 and strangely also works in the quite similar Ubuntu 25.04). Maybe you have an idea, what the root cause could be?

Best regards.

[1] https://buildd.debian.org/status/fetch.php?pkg=jpeg-xl&arch=i386&ver=0.11.1-1&stamp=1739052249&raw=0
[2] https://buildd.debian.org/status/fetch.php?pkg=jpeg-xl&arch=i386&ver=0.11.1-2&stamp=1741995098&raw=0

**Comment by rathann** [comment]
Which gcc version are you using? We build with LTO enabled on Fedora and it works fine:
```
[ 64%] Building CXX object lib/CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o
cd /builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib && /usr/bin/g++ -DFJXL_ENABLE_AVX512=0 -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DJXL_STATIC_DEFINE -DTEST_DATA_PATH=\"/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/testdata\" -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1 -I/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/lib/include -isystem /builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fno-rtti -DNDEBUG -std=c++17 -fPIE -fmacro-prefix-map=/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1=. "-DHWY_DISABLED_TARGETS=(HWY_SSSE3|HWY_AVX3|HWY_AVX3_SPR|HWY_AVX3_ZEN4|HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128|HWY_RVV)" -funwind-tables -fno-omit-frame-pointer -Wno-builtin-macro-redefined -Wall -fmerge-all-constants -fno-builtin-fwrite -fno-builtin-fread -Wextra -Wc++11-compat -Warray-bounds -Wformat-security -Wimplicit-fallthrough -Wno-register -Wno-unused-function -Wno-unused-parameter -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -fsized-deallocation -fno-exceptions -fmath-errno -DJPEGXL_ENABLE_SKCMS=1 -DJPEGXL_ENABLE_TRANSCODE_JPEG=1 -DJPEGXL_ENABLE_BOXES=1 -DHWY_SHARED_DEFINE -MD -MT lib/CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o -MF CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o.d -o CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o -c /builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/lib/extras/dec/color_description_test.cc
...
[ 67%] Linking CXX executable tests/color_description_test
cd /builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib && /usr/bin/cmake -E cmake_link_script CMakeFiles/color_description_test.dir/link.txt --verbose=1
...
/usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fno-rtti -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -fPIE -pie -Wl,--dependency-file=CMakeFiles/color_description_test.dir/link.d CMakeFiles/color_description_test.dir/extras/dec/color_description_test.cc.o -o tests/color_description_test  -Wl,-rpath,/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib libjxl_testlib-internal.a libjxl_extras-internal.a /usr/lib/libgtest_main.so.1.15.2 /usr/lib/libgtest.so.1.15.2 libjxl-internal.a /usr/lib/libhwy.so /usr/lib/libbrotlidec.so /usr/lib/libbrotlicommon.so /usr/lib/libbrotlienc.so libjxl_cms.so.0.11.1 libjxl_threads.so.0.11.1 /usr/lib/libgif.so /usr/lib/libjpeg.so ../third_party/sjpeg/libsjpeg.a /usr/lib/libpng.so /usr/lib/libz.so /usr/lib/libOpenEXR-3_2.so /usr/lib/libOpenEXRUtil-3_2.so /usr/lib/libOpenEXRCore-3_2.so /usr/lib/libIex-3_2.so /usr/lib/libIlmThread-3_2.so /usr/lib/libImath-3_1.so
cd /builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib && /usr/bin/cmake -D TEST_TARGET=color_description_test -D TEST_EXECUTABLE=/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib/tests/color_description_test -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=color_description_test_TESTS -D CTEST_FILE=/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build/lib/color_description_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=240 -D TEST_DISCOVERY_EXTRA_ARGS= -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake/Modules/GoogleTestAddTests.cmake
gmake[2]: Leaving directory '/builddir/build/BUILD/jpegxl-0.11.1-build/libjxl-0.11.1/redhat-linux-build'
[ 68%] Built target color_description_test
```

https://kojipkgs.fedoraproject.org//packages/jpegxl/0.11.1/4.fc44/data/logs/i686/build.log

**Comment by juw** [comment]
This was with gcc 14.2.0 (Debian version 14.2.0-16, i.e. 14.2.0 + update to git 20250130 from the gcc-14 branch).

**Comment by jbicha** [comment]
I can still reproduce this issue with Debian unstable using gcc 15.2.0. There are some small differences in what compiler flags are used between Debian and Ubuntu. [This](https://salsa.debian.org/toolchain-team/gcc/-/blob/master/debian/patches/gcc-distro-specs-ubuntu-doc.diff) is one place that lists differences. A next step is to try those compiler flags on Debian to see if it can make the LTO build succeed there.

**Comment by eustas** [comment]
Will take a look soon

**Comment by eustas** [comment]
(does not build even without LTO...)

**Comment by juw** [comment]
With the release of version 0.12.0 this is fixed by now.
