### ISSUE TITLE
Build failure on armv7hl with GCC

### ISSUE THREAD

**Issue by eclipseo** [libjxl/libjxl#63]
**Describe the bug**
The build fails on armv7hl:

```
In file included from /builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/skcms.cc:2071:
/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/src/Transform_inl.h: In function 'baseline::F baseline::F_from_Half(baseline::U16)':
/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/src/Transform_inl.h:158:26: error: 'float16x4_t' was not declared in this scope; did you mean 'bfloat16x4_t'?
  158 |     return vcvt_f32_f16((float16x4_t)half);
      |                          ^~~~~~~~~~~
      |                          bfloat16x4_t
/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/src/Transform_inl.h:158:12: error: 'vcvt_f32_f16' was not declared in this scope; did you mean 'vcvt_f32_bf16'?
  158 |     return vcvt_f32_f16((float16x4_t)half);
      |            ^~~~~~~~~~~~
      |            vcvt_f32_bf16
/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/src/Transform_inl.h: In function 'baseline::U16 baseline::Half_from_F(baseline::F)':
/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/third_party/skcms/src/Transform_inl.h:187:17: error: 'vcvt_f16_f32' was not declared in this scope; did you mean 'vcvt_bf16_f32'?
  187 |     return (U16)vcvt_f16_f32(f);
      |                 ^~~~~~~~~~~~
      |                 vcvt_bf16_f32
gmake[2]: *** [third_party/CMakeFiles/skcms.dir/build.make:79: third_party/CMakeFiles/skcms.dir/skcms/skcms.cc.o] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/jpeg-xl-v0.3.7-9e9bce86164dc4d01c39eeeb3404d6aed85137b2/armv7hl-redhat-linux-gnueabi'
gmake[1]: *** [CMakeFiles/Makefile2:345: third_party/CMakeFiles/skcms.dir/all] Error 2
```

**To Reproduce**
```
%cmake  -DENABLE_CCACHE=1 \
        -DBUILD_TESTING=OFF \
        -DINSTALL_GTEST:BOOL=OFF \
        -DJPEGXL_ENABLE_BENCHMARK:BOOL=OFF \
        -DJPEGXL_ENABLE_PLUGINS:BOOL=ON \
        -DJPEGXL_FORCE_SYSTEM_BROTLI:BOOL=ON \
        -DJPEGXL_FORCE_SYSTEM_GTEST:BOOL=ON \
        -DJPEGXL_FORCE_SYSTEM_HWY:BOOL=ON \
        -DJPEGXL_WARNINGS_AS_ERRORS:BOOL=OFF \
        -DBUILD_SHARED_LIBS:BOOL=OFF
%cmake_build -- all doc
```

Flags:
```
  CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard'
  LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '
```

**Environment**
 - OS: Fedora Rawhide
 - Compiler version: GCC 11.1.1
 - CPU type:
```
CPU info:
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              5
On-line CPU(s) list: 0-4
Thread(s) per core:  1
Core(s) per socket:  5
Socket(s):           1
Vendor ID:           APM
Model:               2
Model name:          X-Gene
Stepping:            0x3
BogoMIPS:            80.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm aes pmull sha1 sha2 crc32
```
 - libhwy: version 0.12.1
 - cjxl/djxl version string: v0.3.7

Full log available at https://koji.fedoraproject.org/koji/taskinfo?taskID=69038231

**Comment by veluca93** [comment]
I believe this is a bug in [skcms](https://github.com/google/skia/tree/main/third_party/skcms)

**Comment by eclipseo** [comment]
> I believe this is a bug in [skcms](https://github.com/google/skia/tree/main/third_party/skcms)

I will report upstream then, though I doubt it will be quickly fixed.

**Comment by eustas** [comment]
It seems that float16x4_t is behind if-def: `#if defined (__ARM_FP16_FORMAT_IEEE) || defined (__ARM_FP16_FORMAT_ALTERNATIVE)`

Going to check if we could resolve that on our side, or skcms side.

**Comment by eustas** [comment]
https://skia-review.googlesource.com/c/skcms/+/424856
Waiting for review.

**Comment by eustas** [comment]
(reviewer will be back on Monday)

**Comment by eustas** [comment]
Still waiting for review...

**Comment by eclipseo** [comment]
@eustas Was the fix ever merged? Thanks.

**Comment by eustas** [comment]
Nearly. Got the change reviewed. But, like in other chromium-family projects, someone with "committer" rights have to push "submit" button...

**Comment by jonsneyers** [comment]
@eustas Is this still stuck?

**Comment by eclipseo** [comment]
I could not reproduce with the latest version 0.6.1. Everything seems to build correctly with GCC 11.2.1 now.

https://koji.fedoraproject.org/koji/taskinfo?taskID=79132010

**Comment by jonsneyers** [comment]
Nice, closing it in that case - feel free to reopen if there's still an issue.

**Comment by adamburgess** [comment]
I get a similar error on arm64 with alpine and GCC. It started failing in 10f5c38d2d3737464a3a09b2e73f3674641c760e. (the previous commits work)
Clang compiles fine

```
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h: In function 'void jxl::N_NEON::{anonymous}::FastTransposeBlock(const int16_t*, size_t, size_t, size_t, int16_t*, size_t)':
/libjxl/lib/jxl/fast_dct-inl.h:61:62: note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts
   61 |       auto four0 = vtrnq_s32(vreinterpretq_s16_s32(a01.val[0]),
      |                                                              ^
/libjxl/lib/jxl/fast_dct-inl.h:61:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   61 |       auto four0 = vtrnq_s32(vreinterpretq_s16_s32(a01.val[0]),
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:62:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   62 |                              vreinterpretq_s16_s32(a23.val[0]));
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:63:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   63 |       auto four1 = vtrnq_s32(vreinterpretq_s16_s32(a01.val[1]),
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:64:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   64 |                              vreinterpretq_s16_s32(a23.val[1]));
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:74:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   74 |       auto four2 = vtrnq_s32(vreinterpretq_s16_s32(a45.val[0]),
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:75:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   75 |                              vreinterpretq_s16_s32(a67.val[0]));
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:76:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   76 |       auto four3 = vtrnq_s32(vreinterpretq_s16_s32(a45.val[1]),
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
In file included from /libjxl/lib/jxl/fast_dct.cc:13:
/libjxl/lib/jxl/fast_dct-inl.h:77:61: error: cannot convert 'int16x8_t' to 'int32x4_t'
   77 |                              vreinterpretq_s16_s32(a67.val[1]));
      |                                                    ~~~~~~~~~^
      |                                                             |
      |                                                             int16x8_t
In file included from /libjxl/third_party/highway/hwy/ops/arm_neon-inl.h:18,
                 from /libjxl/third_party/highway/hwy/highway.h:303,
                 from /libjxl/lib/jxl/fast_dct.cc:9:
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/include/arm_neon.h:5253:34: note:   initializing argument 1 of 'int16x8_t vreinterpretq_s16_s32(int32x4_t)'
 5253 | vreinterpretq_s16_s32 (int32x4_t __a)
      |                        ~~~~~~~~~~^~~
[ 72%] Building CXX object lib/CMakeFiles/jxl_dec-obj.dir/jxl/fields.cc.o
make[3]: *** [lib/CMakeFiles/jxl_dec-obj.dir/build.make:594: lib/CMakeFiles/jxl_dec-obj.dir/jxl/fast_dct.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:3707: lib/CMakeFiles/jxl_dec-obj.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:5148: tools/CMakeFiles/cjxl.dir/rule] Error 2
make: *** [Makefile:2038: cjxl] Error 2
```

To reproduce on arm64:
```Dockerfile
from alpine:3.14

run apk add git cmake build-base libjpeg-turbo-dev libpng-dev zlib-dev
run git clone https://github.com/libjxl/libjxl.git
workdir /libjxl
run git submodule update --init --recursive
workdir /libjxl/build
run cmake ..
run make -j$(($(nproc) + 1)) cjxl djxl
```
