### ISSUE TITLE
Broken build on Manjaro with 0.3.7.r777.g36ece47-1

### ISSUE THREAD

**Issue by jdoklovic** [libjxl/libjxl#1109]
**Describe the bug**
Manjaro gives an error when building this package.

```
Building libjxl-git...
==> Making package: libjxl-git 0.3.7.r777.g36ece47-1 (Thu 20 Jan 2022 09:26:43 AM CST)

...

[ 54%] Building CXX object lib/CMakeFiles/ac_strategy_test.dir/jxl/ac_strategy_test.cc.o
In file included from /var/tmp/pamac-build-doklovic/libjxl-git/src/libjxl/lib/jxl/ac_strategy_test.cc:13:
/usr/include/hwy/tests/test_util-inl.h:448:3: error: statement not allowed in constexpr function
  HWY_ASSERT(max_pow2 != 0);
  ^
/usr/include/hwy/base.h:144:3: note: expanded from macro 'HWY_ASSERT'
  do {                                    \
  ^
1 error generated.
make[2]: *** [lib/CMakeFiles/ac_strategy_test.dir/build.make:76: lib/CMakeFiles/ac_strategy_test.dir/jxl/ac_strategy_test.cc.o] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-doklovic/libjxl-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:1764: lib/CMakeFiles/ac_strategy_test.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/pamac-build-doklovic/libjxl-git/src/build'
make: *** [Makefile:146: all] Error 2
make: Leaving directory '/var/tmp/pamac-build-doklovic/libjxl-git/src/build'
```

**To Reproduce**
Just try to update the AUR package using the software update tool in Manjaro

**Expected behavior**
it builds without error

**Environment**
- Distributor ID:	ManjaroLinux
- Description:	Manjaro Linux
- Release:	21.2.1
- Codename:	Qonos
- 5.10.89-1-MANJARO

**Comment by TheHardew** [comment]
Edit the PKGBUILD so that it doesn't force highway installed in the system. At least that worked on Arch.

**Comment by eustas** [comment]
From my point of view, there are two problems:
 - should HWY test includes be used in JXL tests?
 - of course, `HWY_ASSERT` should not be used inside `constexpr` function

Will look info both soon.

FWIW, in current codebase I  can't see corresponding code in ToT.

**Comment by eustas** [comment]
Fixed in HWY: https://github.com/google/highway/commit/b0ac61a8ff97509eb2117fb1dc939809afe2bdc0

**Comment by TheHardew** [comment]
At least on Arch it build with system highway, so I think so.

**Comment by mo271** [comment]
> At least on Arch it builds with system highway, so I think so.

Great!
